### ISSUE TITLE
Format of the upmu data files

### ISSUE THREAD

**Issue by hasalaid** [lbnl-cybersecurity/lbnl-cybersecurity.github.io#2]
Hi,

Can you please explain the format of the data files pertaining the to the micropmus?  Is it possible to integrate this directly into a PDC?

**Comment by TheMosquito** [comment]
I am also trying to understand the data files here.  This looks like a very interesting data source but it is difficult to discern what exactly is being presented.  From initial review of the "a6_bu1" files, I think I can see this:
- there are three uPMUs represented in the data ("a6 bus1", "grizzly bus 1_2" and "bank 415")
- for each of these there are 13 data files, which appear to represent the 12 data streams plus the STATE file which has measurements that are all zero -- maybe this is the starting angle for the phase?
- the other 12 files seem to cover 6 samples each for C and L (could this be current and voltage, respectively?)
- I am guessing that the 6 samples are 2 samples each sampled from each of the 3 power phases, if that makes sense
- and finally, the 2 samples of each are pretty clearly angle (ANG) presumably in degrees, and magnitude (MAG) presumably RMS

**Comment by gingeremma81** [comment]
STATE is the GPS lock – 0 means its ok
C is current
L is voltage
Yes for the 3 phases
Mag is magnitude
Ang is angle

there is also a document online on the page which has some more info on the measurements
You should be able to integrate it into a PDC - but that would be something for the researchers utilizing the data to attempt

**Comment by TheMosquito** [comment]
@gingeremma81, Thank you so much for your prompt reply! I wonder if you are the Dr. Emma Stewart who authored the short but enticing paper that drew me here: https://eetd.lbl.gov/sites/all/files/lbnl-1006408_open_upmu_ieee_oct2016.pdf
The above document contains useful details about each of the PMUs used to collect this data, but I do not see the other document you mentioned anywhere on http://powerdata.lbl.gov  Is this document link accidentally missing from that site?  Do you have that document link?
The link provided to the site of the manufacturer of the PCube3 device, and their promotional material was helpful.
Main biggest remaining questions are:
1. what is the unit of measure in the files -- are the values scaled, and if so by how much
2. is the initial phase angle given anywhere
Apologies if these are naive questions.  It is likely obvious that I am not an electric power engineer.  I am just a software engineer who is trying to use your beautiful (amazing, in fact) data set to build a simulation of a PMU in software, and I need some basic understanding of the data for this.  Some of the questions arise because I also want to provide some basic visualization of this data as it is being streamed from the simulated PMU.  If there is any general reference material you could recommend, that would also be very helpful.
Thank you very much for your help (and your data)!

**Comment by gingeremma81** [comment]
Glen,
The document you reference explains the scaling – they are on the low side of potential transformers – so 120V to 7.2 KV for the voltage,  and 5A to (whatever the current transducer is – usually something like 2000A)  you are looking at the scaled values in the csv files
Voltage (L) is in Volts – scaled from a 120V measurement to 7.2kV
C is scaled from a 5A to whatever the CT is is connected too is… in Amps

There isn’t an initial phase angle – the uPMUs are referenced to each other – i.e. the important part is the angle at the sub station (grizzly) minus the angle at the downstream sensors – i.e. grizzly can be considered the reference in this set!

There was a visualization tool online – its down at the moment – but yes interested in anything you have going on in that area!
Thanks
Emma

**Comment by TheMosquito** [comment]
Emma, thank you again for the detailed info you are providing here.  It is very helpful.

I wrote a small program to scour the 3 STATE files to find the longest continuous block of data without much GPS lock loss, and I found the epoch time starting at 1443850272000000000 has 8.01 hours of data with no GPS lock gap exceeding 1 second (120 samples) in any of the 3 PMUs.  So I will be working with an exactly 8 hour block starting at that epoch time.  I wrote another small program to trim the data files down to start at that epoch and collected data from them for 8 hours -- merging the 12 data files for each PMU into a single file for each PMU giving.  Each sample is a single record with one shared timestamp, and 12 samples from that timestamp (3 phases by current and voltage by angle and magnitude).  So the 150+GB input data is now down to 1.8GB (3 files of about 600MB) which makes this more manageable on the Raspberry Pi units I am using as simulated PMUs.  I also encoded the data in JSON for easy consumption in modern programming languages, and included metadata about the source URLs etc..

Now that I have the data in a form I can use easily, I have moved on to look at visualizing this data on a small 320x240 TFT screen on each simulated PMU (Raspberry Pi computer). I then quickly realized that sampling at 120 samples per second means that for 60Hz power there are only 2 samples per full wave!  So now I understand that I will need to compute x, y for each of those two samples, and also compute amplitude of the wave and finally wavelength (or frequency) of the wave if I want to visualize sine waves on these small screens.

I am unfamiliar with the math needed to compute those values from the data, so I need to do some research on that.  If you are able to point me at any reference material (or if you just happen to know the formulae for computing these values) any assistance you could provide would be most appreciated.

Note that I will be looking at a more interesting visualization *comparing* the data from the 3 PMUs after this, but step one for me is to get the simulated PMUs going first.

**Comment by TheMosquito** [comment]
I figured out that these phases are (3D) helixes and that in order to plot the (2D) sine waves (i.e., a lateral projection onto a plane) the amplitude calculation is simply: magnitude * sin(phase angle).  I am plotting the resulting sine waves for voltage of all 3 phases, 120 degrees apart.  Although these waves clearly drift forward and back over time, they are quite symmetrical and relatively stable.  In contrast the sine waves for current intensity, which I am separately plotting, fluctuate much more and are much less symmetrical.  I am also separately plotting the voltage phase angle and magnitude vectors for each of the phases.  Fun stuff.  Thanks again for all of your help.
